// GENERATED by scripts/fx/bake.mjs (npm run fx:atlas) - do not edit.
// Source of truth: the sprite definitions in src/content/fx/sprites-*.ts.
import type { FxAnimMeta } from './types';

export const FX_ANIM_NAMES = [
  'coin_spin',
  'bill_flutter',
  'moneybag',
  'gold_star',
  'heart',
  'crown',
  'brick_chip',
  'hammer',
  'sale_tag',
  'siren',
  'flag_wave',
  'sparkle4',
  'glint_sweep',
  'shine_cross',
  'star_burst',
  'ring_shock',
  'dust_puff',
  'smoke',
  'firework',
  'ray_burst',
  'glow',
  'speed_lines',
  'comet',
  'stamp_splat',
  'hit_lines',
  'confetti_rect',
  'confetti_streamer',
  'confetti_dot',
  'confetti_tri',
  'confetti_diamond',
] as const;

export type FxAnimName = (typeof FX_ANIM_NAMES)[number];

/** Baked device-pixel ratio (raster px per nominal px, before per-sprite k) and reference unit. */
export const FX_BAKE = { dpr: 2, ref: 30 } as const;

/** Paths relative to the app base (public/fx/*). */
export const FX_FILES = { json: 'fx/atlas.json', color: 'fx/atlas-color.webp', mask: 'fx/atlas-mask.webp' } as const;

export const FX_FRAME_TOTAL = 125;

export const FX_ANIMS: Record<FxAnimName, FxAnimMeta> = {
  coin_spin: { atlas: 'color', n: 10, fps: 20, loop: true, w: 48, h: 48, k: 1 },
  bill_flutter: { atlas: 'color', n: 6, fps: 12, loop: true, w: 56, h: 34, k: 1 },
  moneybag: { atlas: 'color', n: 1, fps: 1, loop: false, w: 64, h: 64, k: 1 },
  gold_star: { atlas: 'color', n: 1, fps: 1, loop: false, w: 48, h: 48, k: 1 },
  heart: { atlas: 'color', n: 1, fps: 1, loop: false, w: 48, h: 44, k: 1 },
  crown: { atlas: 'color', n: 1, fps: 1, loop: false, w: 64, h: 52, k: 1 },
  brick_chip: { atlas: 'color', n: 3, fps: 1, loop: false, w: 26, h: 22, k: 1 },
  hammer: { atlas: 'color', n: 1, fps: 1, loop: false, w: 64, h: 64, k: 1 },
  sale_tag: { atlas: 'color', n: 1, fps: 1, loop: false, w: 48, h: 44, k: 1 },
  siren: { atlas: 'color', n: 4, fps: 12, loop: true, w: 64, h: 64, k: 1 },
  flag_wave: { atlas: 'mask', n: 6, fps: 10, loop: true, w: 64, h: 52, k: 1 },
  sparkle4: { atlas: 'mask', n: 6, fps: 20, loop: false, w: 48, h: 48, k: 1 },
  glint_sweep: { atlas: 'mask', n: 8, fps: 24, loop: false, w: 64, h: 64, k: 1 },
  shine_cross: { atlas: 'mask', n: 6, fps: 15, loop: false, w: 96, h: 96, k: 1 },
  star_burst: { atlas: 'mask', n: 8, fps: 24, loop: false, w: 128, h: 128, k: 0.75 },
  ring_shock: { atlas: 'mask', n: 6, fps: 24, loop: false, w: 128, h: 128, k: 0.75 },
  dust_puff: { atlas: 'mask', n: 8, fps: 20, loop: false, w: 96, h: 96, k: 0.75 },
  smoke: { atlas: 'mask', n: 8, fps: 15, loop: false, w: 96, h: 96, k: 0.75 },
  firework: { atlas: 'mask', n: 12, fps: 20, loop: false, w: 128, h: 128, k: 0.75 },
  ray_burst: { atlas: 'mask', n: 1, fps: 1, loop: false, w: 256, h: 256, k: 0.5 },
  glow: { atlas: 'mask', n: 1, fps: 1, loop: false, w: 64, h: 64, k: 1 },
  speed_lines: { atlas: 'mask', n: 4, fps: 20, loop: true, w: 128, h: 64, k: 0.75 },
  comet: { atlas: 'mask', n: 8, fps: 20, loop: true, w: 96, h: 48, k: 0.75 },
  stamp_splat: { atlas: 'mask', n: 5, fps: 24, loop: false, w: 128, h: 128, k: 0.75 },
  hit_lines: { atlas: 'mask', n: 4, fps: 24, loop: false, w: 64, h: 64, k: 1 },
  confetti_rect: { atlas: 'mask', n: 1, fps: 1, loop: false, w: 18, h: 22, k: 1 },
  confetti_streamer: { atlas: 'mask', n: 1, fps: 1, loop: false, w: 18, h: 38, k: 1 },
  confetti_dot: { atlas: 'mask', n: 1, fps: 1, loop: false, w: 18, h: 18, k: 1 },
  confetti_tri: { atlas: 'mask', n: 1, fps: 1, loop: false, w: 20, h: 20, k: 1 },
  confetti_diamond: { atlas: 'mask', n: 1, fps: 1, loop: false, w: 20, h: 22, k: 1 },
};

/** Frame key inside atlas.json: `${anim}/${index}`. */
export const fxFrameKey = (anim: FxAnimName, index: number): string => `${anim}/${index}`;
