// GENERATED by scripts/fx/bake-money.mjs (npm run fx:atlas) - do not edit.
// Source of truth: MONEY_SPRITES in src/content/fx/sprites-money.ts.

export const MONEY_ANIM_NAMES = [
  'coin_spin_gold',
  'coin_spin_silver',
  'coin_spin_bronze',
  'coin_slice_gold',
  'coin_slice_silver',
  'coin_slice_bronze',
  'coin_top_gold',
  'coin_top_silver',
  'coin_top_bronze',
  'coin_burst',
  'vault',
  'bank',
  'plot_sign',
  'dirt_plot',
  'hammer',
  'siren',
  'sparkle4',
  'dust_puff',
] as const;

export type MoneyAnimName = (typeof MONEY_ANIM_NAMES)[number];

/** Paths relative to the app base (public/fx/*). Loaded only by the money stage. */
export const MONEY_FILES = { json: 'fx/money.json', atlas: 'fx/money.webp' } as const;

export const MONEY_FRAME_TOTAL = 60;

/** Nominal size (CSS px at scale 1), frame count, fps, bake shrink, whole-cell frames. */
export const MONEY_ANIMS: Record<MoneyAnimName, { n: number; fps: number; w: number; h: number; k: number; fixedBox: boolean }> = {
  coin_spin_gold: { n: 8, fps: 20, w: 48, h: 48, k: 1.2, fixedBox: true },
  coin_spin_silver: { n: 8, fps: 20, w: 48, h: 48, k: 1.2, fixedBox: true },
  coin_spin_bronze: { n: 8, fps: 20, w: 48, h: 48, k: 1.2, fixedBox: true },
  coin_slice_gold: { n: 1, fps: 1, w: 40, h: 6, k: 2, fixedBox: false },
  coin_slice_silver: { n: 1, fps: 1, w: 40, h: 6, k: 2, fixedBox: false },
  coin_slice_bronze: { n: 1, fps: 1, w: 40, h: 6, k: 2, fixedBox: false },
  coin_top_gold: { n: 1, fps: 1, w: 40, h: 14, k: 2, fixedBox: false },
  coin_top_silver: { n: 1, fps: 1, w: 40, h: 14, k: 2, fixedBox: false },
  coin_top_bronze: { n: 1, fps: 1, w: 40, h: 14, k: 2, fixedBox: false },
  coin_burst: { n: 6, fps: 20, w: 64, h: 64, k: 0.5, fixedBox: false },
  vault: { n: 2, fps: 1, w: 96, h: 96, k: 0.3, fixedBox: false },
  bank: { n: 1, fps: 1, w: 96, h: 96, k: 0.3, fixedBox: false },
  plot_sign: { n: 1, fps: 1, w: 64, h: 72, k: 0.3, fixedBox: false },
  dirt_plot: { n: 1, fps: 1, w: 128, h: 76, k: 0.3, fixedBox: false },
  hammer: { n: 1, fps: 1, w: 64, h: 64, k: 0.75, fixedBox: false },
  siren: { n: 4, fps: 12, w: 64, h: 64, k: 0.6, fixedBox: false },
  sparkle4: { n: 6, fps: 20, w: 48, h: 48, k: 0.45, fixedBox: false },
  dust_puff: { n: 8, fps: 20, w: 96, h: 96, k: 0.34, fixedBox: false },
};

/** Standalone repeatable tiles (wallet coin columns): name -> path and raster size. */
export const MONEY_TILES: Record<string, { file: string; w: number; h: number }> = {
  coin_slice_gold: { file: 'fx/money-tile-coin_slice_gold.webp', w: 160, h: 24 },
  coin_slice_silver: { file: 'fx/money-tile-coin_slice_silver.webp', w: 160, h: 24 },
  coin_slice_bronze: { file: 'fx/money-tile-coin_slice_bronze.webp', w: 160, h: 24 },
};
