// GENERATED by scripts/dealer/bake-sob.py - do not edit.
// The crying dealer's sob frames (docs/MONEY-EVENTS.md §14.5): public/dealer/sad.webp baked
// with sprite-gen Breathe { depth: 0.08, breaths: 1, lag: 0.1 }.

/** The sheet: `cells` phases side by side, each `cell` px square. */
export const SOB_SHEET = 'dealer/sad-sob.webp';

/** headDy: per phase, how far the (rigid) head sits below where the still (sad.webp, SAD_EYES) has it, in sprite px. */
export const SOB = { cells: 6, cell: 320, headDy: [-5, 8, 9, 3, -6, -13] } as const;
