// Emits src/content/icons/{landmarks,tokens,buildings,ui}.ts from scripts/icons-src/*.mjs
// Usage: node scripts/build-icons.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(here, '..', 'src', 'content', 'icons');
const jobs = [
  ['landmarks', 'LANDMARK_ICONS', 'Landmark, hub, corner and special-space icons (64x64, flat, original).'],
  ['tokens', 'TOKEN_ICONS', 'Player tokens (64x64). Main body uses currentColor so the player color tints it.'],
  ['buildings', 'BUILDING_ICONS', 'Buildings, pot, coin, dice faces and card icons (64x64). Accent uses currentColor.'],
  ['ui', 'UI_ICONS', 'Monochrome 24x24 UI icons, 2px stroke, currentColor.'],
  ['logo', 'LOGO_SVG', 'LOT & ROLL emblem (dice on a land plot with a roll swoosh).'],
];
fs.mkdirSync(out, { recursive: true });
for (const [file, name, doc] of jobs) {
  if (!fs.existsSync(path.join(here, 'icons-src', `${file}.mjs`))) continue;
  const src = pathToFileURL(path.join(here, 'icons-src', `${file}.mjs`)).href;
  const map = (await import(src)).default;
  if (typeof map === 'string') {
    if (map.includes('`') || map.includes('${')) throw new Error('logo contains backtick');
    fs.writeFileSync(path.join(out, `${file}.ts`), `// GENERATED by scripts/build-icons.mjs from scripts/icons-src/${file}.mjs - edit the source, then rebuild.\n// ${doc}\n// All artwork is original to this project.\nexport const ${name} = \`${map}\`;\n`);
    console.log(`${file}.ts: 1 icon`);
    continue;
  }
  const lines = Object.entries(map).map(([k, v]) => {
    if (v.includes('`') || v.includes('${')) throw new Error(`${file}:${k} contains backtick or \${`);
    return `  '${k}': \`${v}\`,`;
  });
  const ts = `// GENERATED by scripts/build-icons.mjs from scripts/icons-src/${file}.mjs - edit the source, then rebuild.\n// ${doc}\n// All artwork is original to this project.\nexport const ${name}: Record<string, string> = {\n${lines.join('\n')}\n};\n`;
  fs.writeFileSync(path.join(out, `${file}.ts`), ts);
  console.log(`${file}.ts: ${Object.keys(map).length} icons`);
}
